# render.yaml
services:
  - type: web
    name: rails-pwa-app
    env: ruby
    plan: free
    buildCommand: "bundle install && yarn install && bundle exec rake db:migrate"
    startCommand: "bundle exec rails server -p 3000"
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false