services:
  - type: web
    name: rails-pwa-app
    env: ruby
    plan: free
    buildCommand: "bundle install && bundle exec rake db:migrate"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false